# Change these first
owner: EnvyxLinzie # Your GitHub organization or username, where this repository lives
repo: times-hzfx # The name of this repository

sites:
  - name: HorizonTimes
    url: https://times.horizonfx.id
  - name: DataHorizon
    url: https://data.horizonfx.id
  - name: HorizonFx
    url: https://horizonfx.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.horizonfx.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime HZFX
  introTitle: "**Uptime** Website Horizonfx.id beserta Log Update Web."
  introMessage: "Log Update 
  1.0.2
  - Penambahan Fitur News Feed
  - Update App Horizonfx Bug Scrolling up Jadi Refresh"

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
